blog_post/urls.py
from django.urls import path
from .views import *


urlpatterns = [
	path('blog-list/', blog_list, name='blog-list'),
	path('blog-single/<str:pk>', blog_single, name='blog-single'),
	path('tag/<slug:tag_slug>/', posts_with_tag, name='post_list_by_tag'),
    path('like/<int:pk>/', like_blog, name='like_blog'),
]

hotel_management/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings 
from django.conf.urls.static import static
from django.conf.urls.i18n import i18n_patterns




urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('user.urls')),
    path('i18n/', include('django.conf.urls.i18n')),
    path('blog/', include('blog_post.urls')),
    path('manager/', include('hotel_manager.urls', namespace="hotel_manager")),
    path('accounts/', include('allauth.urls')), #google integration
]

if settings.DEBUG: # new
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    
    urlpatterns += i18n_patterns(
    path('', include('user.urls')),
    path('blog/', include('blog_post.urls')),
    )


if 'rosetta' in settings.INSTALLED_APPS:
    urlpatterns += [
        re_path(r'^rosetta/', include('rosetta.urls'))
    ]

hotel_manager/urls.py
from django.urls import path
from .views import *


app_name = "hotel_manager"

urlpatterns = [
    path('', dashboard, name='dashboard'),
    path('rooms/', Rooms.as_view(), name="rooms"),
    path("room-create/", RoomCreate.as_view(), name="room-create"),
    path("room-update/<int:pk>/", RoomUpdate.as_view(), name="room-update"),
    path("room-delete/<int:pk>/",room_delete, name="room-delete"),


    path("posts/", BlogPosts.as_view(), name="posts"),
    path("post-create/", PostCreate.as_view(), name="post-create"),
    path("post-update/<int:pk>/",  PostUpdate.as_view(), name="post-update"),
    path("post-delete/<int:pk>/",post_delete, name="post-delete"),

    path("restaurant/", Restaurant.as_view(), name="restaurant"),
    path('restaurant-create/', RestaurantCreate.as_view(), name="restaurant-create"),
    path("restaurant-update/<int:pk>/", RestaurantUpdate.as_view(), name="restaurant-update"),
    path('restaurant-delete/<int:pk>/', restaurant_delete, name="restaurant-delete"),

    path("guests/", Guests.as_view(),name="guests"),

    path('room-category/', RoomCategory.as_view(), name="room-category"),
    path('room-category-create', RoomCategoryCreate.as_view(), name="room-category-create"),


    path('reservation-list/', Reservation.as_view(), name="reservation-list"),

    path('testimonials/', Testimonials.as_view(), name="testimonials"),
    path('testimonials-create/', TestimonialsCreate.as_view(), name="testimonials-create"),
    path('testimonials-update/<int:pk>/', TestimonialsUpdate.as_view(), name="testimonials-update"),
    path('testimonials-delete/<int:pk>/', testimonials_delete, name="testimonials-delete"),

    path('instagram-update/<int:pk>/', InstagramUpdateView.as_view(), name="instagram-update"),
    path('instagram-delete/<int:pk>/', instagram_delete, name="instagram-delete"),
]

user/urls.py
from django.urls import path
from .views import *



urlpatterns = [
	path('', main, name='home'),
	path('main2/', main2, name='main2'),
	path('contact/', contact, name='contact'),
	path('about/', about, name='about'),


	path('user/', user_profile, name='user_profile'),
	path('profile_settings/', profile_settings, name='profile_settings'),
	path('rooms/', rooms, name='rooms'),
	path('room-single/<str:pk>/', room_single, name='room-single'),

	path('booking/<str:pk>/', booking, name='booking'),
	path('cancel_booking/<str:pk>/', cancel_booking, name='cancel_booking'),
	
	# stripe 
	path('success/', SuccessView.as_view(), name='success'),
    path('create-checkout-session/<pk>/', CreateCheckoutSessionView.as_view(), name='create-checkout-session'),
	# stripe 

	path('restaurant/', restaurant, name='restaurant'),

	path('signup/', user_signup, name='user_signup'),
	path('login/', user_login, name='user_login'),
	path('logout/', userLogout, name='logout'),

]

blog_post/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import tree
from taggit.managers import TaggableManager
from user.models import Guest


class Blog(models.Model):
	blog_image = models.ImageField(upload_to='images/blog_images')
	blog_heading = models.CharField(max_length=100, null=True)
	blog_text = models.CharField(max_length=255, null=True)
	date_created = models.DateTimeField(auto_now_add=True)
	likes = models.ManyToManyField(User, related_name="blog_posts")

	tags = TaggableManager()


	def total_likes(self):
		return self.likes.count()


	def __str__(self):
		return self.blog_heading

 
class BlogComment(models.Model):
	message = models.CharField(max_length=255, null=True)
	date_created = models.DateTimeField(auto_now_add=True)
	post = models.ForeignKey(Blog, on_delete=models.CASCADE, null=True, related_name='comments')
	guest = models.ForeignKey(Guest, on_delete=models.CASCADE, null=True)
	active = models.BooleanField(default=True)
	

	def __str__(self):
		return self.message



hotel_manager/models.py
from django.db import models

# Create your models here.

blog_post/forms.py
from django import forms
from .models import *


class BlogCommentForm(forms.ModelForm):
	class Meta:
		model = BlogComment
		fields = ('message',)

hotel_manager/forms.py
from django import forms
from user.models import *
from blog_post.models import *


class RoomForm(forms.ModelForm):
    class Meta:
        model = Room
        fields = "__all__"


class BlogForm(forms.ModelForm):
    class Meta:
        model = Blog
        fields = "__all__"


class RestaurantForm(forms.ModelForm):
    class Meta:
        model = Food
        fields = "__all__"

class RoomCategoryForm(forms.ModelForm):
    class Meta:
        model = RoomCategory
        fields = "__all__"


class TestimonialsForm(forms.ModelForm):
    class Meta:
        model = Testimonials
        fields = "__all__"


class InstagramUpdateForm(forms.ModelForm):
    class Meta:
        model = Instagram
        fields = "__all__"

blog_post/views.py
from django.shortcuts import get_object_or_404, render, redirect, reverse
from .forms import BlogCommentForm
from django.core.mail import send_mail
from .models import *
from django.core.paginator import Paginator, EmptyPage,\
								  PageNotAnInteger

from django.contrib.auth.decorators import login_required
from taggit.models import Tag
from user.models import Guest
from user.decorators import *


def blog_list(request):
	blogs = Blog.objects.all()
	paginator = Paginator(blogs, 4) # 3 posts in each page
	page = request.GET.get('page')
	try:
		blogs = paginator.page(page)
	except PageNotAnInteger:
		# If page is not an integer deliver the first page
		blogs = paginator.page(1)
	except EmptyPage:
		# If page is out of range deliver last page of results
		blogs = paginator.page(paginator.num_pages)
	context = {'blogs': blogs}
	return render(request, 'blog_post/blog_list.html', context)


def like_blog(request, pk):
	blog = Blog.objects.get(id=pk)
	if request.method == 'POST':
		liked = False
		if blog.likes.filter(id=request.user.id).exists():
			blog.likes.remove(request.user)
			liked = False
		else:
			blog.likes.add(request.user)
			liked = True
	return HttpResponseRedirect(reverse('blog-single', args=[str(pk)]))



def blog_single(request, pk):
	blogs = Blog.objects.order_by("-date_created")[:3]
	blog = Blog.objects.get(id=pk)
	comments = blog.comments.filter(active=True)
	
	# liking section 
	total_likes = blog.total_likes()
	liked = False
	if blog.likes.filter(id=request.user.id).exists():
		liked = True


	new_comment = None	
	tags =Tag.objects.all()

	if request.method == 'POST':
		blog_comment_form = BlogCommentForm(data=request.POST)
		if request.user.is_authenticated:
			if blog_comment_form.is_valid():
				new_comment = blog_comment_form.save(commit=False)
				new_comment.post = blog
				new_comment.guest = Guest.objects.get(user=request.user) 
				new_comment.save()
		else:
			return redirect('user_login')
	else:
		blog_comment_form = BlogCommentForm()


	context = {'blog_comment_form': blog_comment_form,
	'blog': blog, 'blogs': blogs, 'comments': comments, 'tags':tags, 'total_likes': total_likes, 'liked':liked}
	return render(request, 'blog_post/blog_single.html', context)



def posts_with_tag(request, tag_slug=None):
	blogs = Blog.objects.all()
	tag = None

	if tag_slug:
		tag = get_object_or_404(Tag, slug=tag_slug)
		blogs = blogs.filter(tags__in = [tag])
	paginator = Paginator(blogs, 4) # 3 posts in each page
	page = request.GET.get('page')
	try:
		blogs = paginator.page(page)
	except PageNotAnInteger:
		# If page is not an integer deliver the first page
		blogs = paginator.page(1)
	except EmptyPage:
		# If page is out of range deliver last page of results
		blogs = paginator.page(paginator.num_pages)
	context = {'tag':tag, 'blogs':blogs}

	return render(request, 'blog_post/posts_with_tags.html', context)

hotel_manager/views.py
from django.shortcuts import redirect, render, reverse
from django.views.generic import CreateView, ListView, DeleteView, DeleteView
from django.views.generic.edit import UpdateView, FormView
from user.models import *
from blog_post.models import *
from .forms import *
from .models import *
from user.decorators import *
from django.contrib.auth.decorators import login_required

@login_required(login_url='user_login')
@admin_only
def dashboard(request):
	overall = 0
	total_price = Finance.objects.all()
	for price in total_price:
		overall += price.room_price
	finances = Finance.objects.all()
	instagram_images = Instagram.objects.all()
	hotel_amenities = HotelAmenities.objects.all()
	context = {'overall': overall, 'finances': finances, 'instagram_images':instagram_images, 'hotel_amenities':hotel_amenities}
	return render(request, 'hotel_manager/dashboard.html', context)


class Rooms(ListView):
	template_name = "hotel_manager/rooms.html"
	queryset = Room.objects.filter(status="Available")
	context_object_name = "rooms"


class RoomCreate(CreateView):
	template_name = "hotel_manager/manager_create_update.html"
	form_class = RoomForm

	def get_success_url(self):
		return reverse("hotel_manager:rooms")


class RoomUpdate(UpdateView):
	template_name = "hotel_manager/manager_create_update.html"
	queryset = Room.objects.all()
	form_class = RoomForm

	def get_success_url(self):
		return reverse("hotel_manager:rooms")


def room_delete(request, pk):
	room = Room.objects.get(id=pk)
	room.delete()
	return redirect("hotel_manager:rooms")


class BlogPosts(ListView):
	queryset = Blog.objects.all()
	template_name = "hotel_manager/blog-posts.html"
	context_object_name = "posts"


class PostCreate(CreateView):
	template_name = "hotel_manager/manager_create_update.html"
	form_class = BlogForm

	def get_success_url(self):
		return reverse("hotel_manager:posts")


class PostUpdate(UpdateView):
	template_name = "hotel_manager/manager_create_update.html"
	queryset = Blog.objects.all()
	form_class = BlogForm

	def get_success_url(self):
		return reverse("hotel_manager:posts")


def post_delete(request, pk):
	post = Blog.objects.get(id=pk)
	post.delete()
	return redirect("hotel_manager:posts")




class Restaurant(ListView):
	template_name = "hotel_manager/restaurant-foods.html"
	queryset = Food.objects.all()
	context_object_name = "foods"

class RestaurantCreate(CreateView):
	template_name = "hotel_manager/manager_create_update.html"
	form_class = RestaurantForm

	def get_success_url(self):
		return reverse("hotel_manager:restaurant")


class RestaurantUpdate(UpdateView):
	template_name = "hotel_manager/manager_create_update.html"
	queryset = Food.objects.all()
	form_class = RestaurantForm

	def get_success_url(self):
		return reverse("hotel_manager:restaurant")


def restaurant_delete(request, pk):
	post = Food.objects.get(id=pk)
	post.delete()
	return redirect("hotel_manager:restaurant")

class Guests(ListView):
	template_name = "hotel_manager/guests.html"
	queryset = Guest.objects.all()
	context_object_name = "guests"


class RoomCategory(ListView):
	template_name = "hotel_manager/room_category.html"
	queryset = RoomCategory.objects.all()
	context_object_name = "room_category"



class RoomCategoryCreate(CreateView):
	template_name = "hotel_manager/manager_create_update.html"
	form_class = RoomCategoryForm

	def get_success_url(self):
		return reverse("hotel_manager:room-category")



class Reservation(ListView):
	template_name = "hotel_manager/reservation.html"
	queryset = Reservation.objects.all()
	context_object_name = "reservations"

	def get_success_url(self):
		return reverse('hotel_manager:reservation-list')


class Testimonials(ListView):
	template_name = "hotel_manager/testimonials.html"
	queryset = Testimonials.objects.all()
	context_object_name = "testimonials"

	def get_success_url(self):
		return reverse('hotel_manager:testimonials')


class TestimonialsCreate(CreateView):
	template_name = "hotel_manager/manager_create_update.html"
	form_class = TestimonialsForm

	def get_success_url(self):
		return reverse("hotel_manager:testimonials")


# def testimonials_update(request, pk):
# 	testimonial = Testimonials.objects.get(id=pk)
# 	forma = TestimonialsUpdateForm
#
# 	if request.method == "POST":
# 		forma = TestimonialsUpdateForm(request.POST, instance=testimonial)
# 		if forma.is_valid():
# 			forma.save()
# 			return redirect("hotel_manager:testimonials")
# 	context = {'form': forma}
# 	return render(request, 'hotel_manager/manager_create_update.html', context)
class TestimonialsUpdate(UpdateView):
	template_name = "hotel_manager/manager_create_update.html"
	# queryset = Testimonials.objects.all()
	model = Testimonials
	form_class = TestimonialsForm

	def get_success_url(self):
		return reverse("hotel_manager:testimonials")


def testimonials_delete(request, pk):
	testimonial = Testimonials.objects.get(id=pk)
	testimonial.delete()
	return redirect('hotel_manager:testimonials')


class InstagramUpdateView(UpdateView):
	model = Instagram
	form_class = InstagramUpdateForm
	template_name = "hotel_manager/manager_create_update.html"

	def get_success_url(self):
		return reverse("hotel_manager:dashboard")


def instagram_delete(request, pk):
	image = Instagram.objects.get(id=pk)
	image.delete()
	return redirect("hotel_manager:dashboard")


hotel_manager/templates/hotel_manager/blog-posts.html
{% extends 'hotel_manager/base.html' %}
{% block content %}
<!-- MAIN CONTENT-->
<div class="main-content">
    <div class="section__content section__content--p30">
        <div class="container-fluid">
            <div class="row">
                <div class="col-lg-12">
                    <div class="table-responsive table--no-card m-b-30">

                        <div class="table-data__tool">
                            <div class="table-data__tool-right">
                                <a class="au-btn au-btn-icon au-btn--green au-btn--small" href="{% url 'hotel_manager:post-create' %}">
                                    <i class="zmdi zmdi-plus"></i>add item</a>
                            </div>
                        </div>

                        <div class="table-responsive table-responsive-data2">
                            <table class="table table-borderless table-striped table-earning">
                                <thead>
                                    <tr>
                                        <th>Post heading</th>
                                        <th>Create Date</th>
                                        <th>Post Image</th>
                                        <th></th>
                                    </tr>
                                </thead>
                                <tbody>
                                    {% for post in posts %}
                                    <tr>
                                        <td>{{post.blog_heading}}</td>
                                        <td>{{post.date_created}}</td>
                                        <td><img src="{{post.blog_image.url}}" alt="" width="100"></td>

                                        <td><a class="btn btn-outline-info"
                                                href="{% url 'hotel_manager:post-update' post.id %}">Update</a>
                                            <a class="btn btn-outline-danger" href="{% url 'hotel_manager:post-delete' post.id %}">Delete</a>
                                        </td>
                                    </tr>
    
                                    {% endfor %}
                                </tbody>
                            </table>
                        </div>




                    </div>
                </div>

            </div>

        </div>

    </div>

</div>


{% endblock %}

hotel_manager/templates/hotel_manager/dashboard.html
{% extends 'hotel_manager/base.html' %}

{% block content %}
{% load static %}
<!-- MAIN CONTENT-->
<div class="main-content">
    <div class="section__content section__content--p30">
        <div class="container-fluid">
            <div class="row m-t-25">
                <div class="col-sm-6 col-lg-3">
                    <div class="overview-item overview-item--c1">
                        <div class="overview__inner">
                            <div class="overview-box clearfix">
                                <div class="icon">
                                    <i class="zmdi zmdi-account-o"></i>
                                </div>
                                <div class="text">
                                    <h2>1000</h2>
                                    <span>Hotel Staff</span>
                                </div>
                            </div>
                            <div class="overview-chart">
                                <canvas id="widgetChart1"></canvas>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-sm-6 col-lg-3">
                    <div class="overview-item overview-item--c4">
                        <div class="overview__inner">
                            <div class="overview-box clearfix">
                                <div class="icon">
                                    <i class="zmdi zmdi-money"></i>
                                </div>
                                <div class="text">
                                    <h2>$ {{overall}}</h2>
                                    <span>total earnings</span>
                                </div>
                            </div>
                            <div class="overview-chart">
                                <canvas id="widgetChart4"></canvas>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

            <h2 class="title-1">Financial Situation</h2>
            <div class="row">
                <div class="col-md-12">
                    <!-- DATA TABLE -->
                    <div class="table-responsive table-responsive-data2">
                        <table class="table table-data2">
                            <thead>
                            <tr>
                                <th>User Image</th>
                                <th>Username</th>
                                <th>Email</th>
                                <th>Room Price</th>
                                <th>Payment Date</th>
                            </tr>
                            </thead>
                            <tbody>
                            {% for finance in finances %}
                            <tr class="tr-shadow">
                                <td><img src="{{finance.customer.profile_pic.url}}" alt="" width="100"
                                         class="rounded-circle"></td>
                                <td>{{finance.customer.user.username}}</td>
                                <td>
                                    <span class="block-email">{{finance.email}}</span>
                                </td>
                                <td>
                                    <span class="status--process">$ {{finance.room_price}}</span>
                                </td>
                                <td>{{finance.received_date}}</td>
                            </tr>
                            {% endfor %}
                            </tbody>
                        </table>
                    </div>
                    <!-- END DATA TABLE -->
                </div>
            </div>

            <h2 class="title-1">Hotel Amenities</h2>

            <div class="row m-t-25">
                {% for amenity in hotel_amenities %}
                <ul class="list-group">
                    <li class="list-group-item">{{amenity.heading}}</li>
                </ul>
                {% endfor %}
            </div>

            <h2 class="title-1">Instagram Images</h2>
            <div class="row">

                {% for instagram in instagram_images %}
                <div class="col-lg-4">
                    <div class="card">
                        <img src="{{instagram.image.url}}" alt="" class="">
                        <div class="card-body text-center">
                            <a href="{% url 'hotel_manager:instagram-update' instagram.id %}" class="btn btn-primary">Update</a>
                            <a href="{% url 'hotel_manager:instagram-delete' instagram.id  %}"
                               class="btn btn-outline-danger">Delete</a>
                        </div>
                    </div>

                </div>
                {% endfor %}
            </div>


        </div>
    </div>
</div>
<!-- END MAIN CONTENT-->
{% endblock %}

hotel_manager/templates/hotel_manager/manager_create_update.html
{% extends 'hotel_manager/base.html' %}
{% load static %}
{% block content %}

<!-- MAIN CONTENT-->
<div class="main-content">
    <div class="section__content section__content--p30">
        <div class="container-fluid">
            <div class="row">
                <div class="col-lg-12">
                    <div class="table-responsive table--no-card m-b-30">

                        <form action="" method="POST" enctype="multipart/form-data">
                            {% csrf_token %}
                            {{form.as_p}}
                            <input type="submit" class="btn btn-info" value="Save">
                        </form>

                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

hotel_manager/templates/hotel_manager/restaurant-foods.html
{% extends 'hotel_manager/base.html' %}
{% block content %}
<!-- MAIN CONTENT-->
<div class="main-content">
    <div class="section__content section__content--p30">
        <div class="container-fluid">
            <div class="table-data__tool">
                <div class="table-data__tool-right">
                    <a class="au-btn au-btn-icon au-btn--green au-btn--small"
                        href="{% url 'hotel_manager:restaurant-create' %}">
                        <i class="zmdi zmdi-plus"></i>add New Food</a>
                </div>
            </div>
            <div class="row">

                {% for food in foods %}
                <div class="col-lg-4">
                    <div class="card">
                        <img src="{{food.food_image.url}}" alt="" class="">
                        <div class="card-body text-center">
                            <p>{{food.food_name}}</p>
                            <p>$ {{food.price}}</p>
                            <a href="{% url 'hotel_manager:restaurant-update' food.id %}" class="btn btn-primary">Update</a>
                            <a href="{% url 'hotel_manager:restaurant-delete' food.id %}" class="btn btn-outline-danger">Delete</a>
                        </div>
                    </div>

                </div>
                {% endfor %}
            </div>

        </div>

    </div>

</div>


{% endblock %}

hotel_manager/templates/hotel_manager/room_category.html
{% extends 'hotel_manager/base.html' %}
{% block content %}
<!-- MAIN CONTENT-->
<div class="main-content">
    <div class="section__content section__content--p30">
        <div class="container-fluid">
            <div class="row">
                <div class="col-lg-12">
                    <div class="table-responsive table--no-card m-b-30">

                        <div class="table-data__tool">
                            <div class="table-data__tool-right">
                                <a class="au-btn au-btn-icon au-btn--green au-btn--small" href="{% url 'hotel_manager:room-category-create' %}">
                                    <i class="zmdi zmdi-plus"></i>add item</a>
                            </div>
                        </div>


                        <ul class="list-group">
                        {% for category in room_category %}
                          <li class="list-group-item list-group-item-success h1">{{category.name}}</li>
                            {% endfor %}
                        </ul>

                    </div>
                </div>

            </div>

        </div>

    </div>

</div>


{% endblock %}

hotel_manager/templates/hotel_manager/rooms.html
{% extends 'hotel_manager/base.html' %}
{% block content %}
<!-- MAIN CONTENT-->
<div class="main-content">
    <div class="section__content section__content--p30">
        <div class="container-fluid">
            <div class="row">
                <div class="col-lg-12">

                    <div class="table-data__tool">
                        <div class="table-data__tool-right">
                            <a class="au-btn au-btn-icon au-btn--green au-btn--small" href="{% url 'hotel_manager:room-create' %}">
                                <i class="zmdi zmdi-plus"></i>add Room</a>
                        </div>
                    </div>

                    <div class="table-responsive table--no-card m-b-30">
                        <table class="table table-borderless table-striped table-earning">
                            <thead>
                                <tr>
                                    <th>Room Category</th>
                                    <th>Room Number</th>
                                    <th class="text-right">Price(per night)</th>
                                    <th>Status</th>
                                    <th></th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for room in rooms %}
                                <tr>
                                    <td>{{room.category.name}} room</td>

                                    <td class="text-center">{{room.room_number}}</td>
                                    <td class="text-center">$ {{room.price}}</td>
                                    <td>{{room.status}}</td>
                                    <td><a class="btn btn-outline-info"
                                            href="{% url 'hotel_manager:room-update' room.id %}">Update</a>
                                        <a class="btn btn-outline-danger" href="{% url 'hotel_manager:room-delete' room.id %}">Delete</a>
                                    </td>
                                </tr>

                                {% endfor %}
                            </tbody>
                        </table>





                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

hotel_manager/templates/hotel_manager/testimonials.html
{% extends 'hotel_manager/base.html' %}
{% load static %}
{% block content %}

<!-- MAIN CONTENT-->
<div class="main-content">
    <div class="section__content section__content--p30">
        <div class="container-fluid">
            <div class="row">
                <div class="col-lg-12">
                    <div class="table-data__tool">
                        <div class="table-data__tool-right">
                            <a class="au-btn au-btn-icon au-btn--green au-btn--small"
                               href="{% url 'hotel_manager:testimonials-create' %}">
                                <i class="zmdi zmdi-plus"></i>add Testimonials</a>
                        </div>
                    </div>
                </div>
            </div>
            <div class="row">
                {% for testimonial in testimonials %}
                <div class="col-lg-6">
                    <div class="card mb-3" style="max-width: 540px;">
                        <div class="row g-0">
                            <div class="col-md-4">
                                <img src="{{testimonial.image.url}}" class="img-fluid rounded-start" alt="...">
                            </div>
                            <div class="col-md-8">
                                <div class="card-body">
                                    <h5 class="card-title">{{testimonial.name}}</h5>
                                    <p class="card-text">{{testimonial.comment}}</p>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                {% endfor %}
            </div>
        </div>
    </div>
</div>
{% endblock %}