hotel_management/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings 
from django.conf.urls.static import static
from django.conf.urls.i18n import i18n_patterns




urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('user.urls')),
    path('i18n/', include('django.conf.urls.i18n')),
    path('blog/', include('blog_post.urls')),
    path('manager/', include('hotel_manager.urls', namespace="hotel_manager")),
    path('accounts/', include('allauth.urls')), #google integration
]

if settings.DEBUG: # new
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    
    urlpatterns += i18n_patterns(
    path('', include('user.urls')),
    path('blog/', include('blog_post.urls')),
    )


if 'rosetta' in settings.INSTALLED_APPS:
    urlpatterns += [
        re_path(r'^rosetta/', include('rosetta.urls'))
    ]

hotel_manager/urls.py
from django.urls import path
from .views import *


app_name = "hotel_manager"

urlpatterns = [
    path('', dashboard, name='dashboard'),
    path('rooms/', Rooms.as_view(), name="rooms"),
    path("room-create/", RoomCreate.as_view(), name="room-create"),
    path("room-update/<int:pk>/", RoomUpdate.as_view(), name="room-update"),
    path("room-delete/<int:pk>/",room_delete, name="room-delete"),


    path("posts/", BlogPosts.as_view(), name="posts"),
    path("post-create/", PostCreate.as_view(), name="post-create"),
    path("post-update/<int:pk>/",  PostUpdate.as_view(), name="post-update"),
    path("post-delete/<int:pk>/",post_delete, name="post-delete"),

    path("restaurant/", Restaurant.as_view(), name="restaurant"),
    path('restaurant-create/', RestaurantCreate.as_view(), name="restaurant-create"),
    path("restaurant-update/<int:pk>/", RestaurantUpdate.as_view(), name="restaurant-update"),
    path('restaurant-delete/<int:pk>/', restaurant_delete, name="restaurant-delete"),

    path("guests/", Guests.as_view(),name="guests"),

    path('room-category/', RoomCategory.as_view(), name="room-category"),
    path('room-category-create', RoomCategoryCreate.as_view(), name="room-category-create"),


    path('reservation-list/', Reservation.as_view(), name="reservation-list"),

    path('testimonials/', Testimonials.as_view(), name="testimonials"),
    path('testimonials-create/', TestimonialsCreate.as_view(), name="testimonials-create"),
    path('testimonials-update/<int:pk>/', TestimonialsUpdate.as_view(), name="testimonials-update"),
    path('testimonials-delete/<int:pk>/', testimonials_delete, name="testimonials-delete"),

    path('instagram-update/<int:pk>/', InstagramUpdateView.as_view(), name="instagram-update"),
    path('instagram-delete/<int:pk>/', instagram_delete, name="instagram-delete"),
]

user/urls.py
from django.urls import path
from .views import *



urlpatterns = [
	path('', main, name='home'),
	path('main2/', main2, name='main2'),
	path('contact/', contact, name='contact'),
	path('about/', about, name='about'),


	path('user/', user_profile, name='user_profile'),
	path('profile_settings/', profile_settings, name='profile_settings'),
	path('rooms/', rooms, name='rooms'),
	path('room-single/<str:pk>/', room_single, name='room-single'),

	path('booking/<str:pk>/', booking, name='booking'),
	path('cancel_booking/<str:pk>/', cancel_booking, name='cancel_booking'),
	
	# stripe 
	path('success/', SuccessView.as_view(), name='success'),
    path('create-checkout-session/<pk>/', CreateCheckoutSessionView.as_view(), name='create-checkout-session'),
	# stripe 

	path('restaurant/', restaurant, name='restaurant'),

	path('signup/', user_signup, name='user_signup'),
	path('login/', user_login, name='user_login'),
	path('logout/', userLogout, name='logout'),

]

templates/footer.html
{% load i18n %}
<footer class="ftco-footer ftco-bg-dark ftco-section">
    <div class="container">
      <div class="row mb-5">
        <div class="col-md">
          <div class="ftco-footer-widget mb-4">
            <h2 class="ftco-heading-2">{% trans 'Hilton Hotel' %}</h2>
            <p>{% trans 'Unlock new memories at our hotels around the world.' %}</p>
            <ul class="ftco-footer-social list-unstyled float-md-left float-lft mt-5">
              <li class="ftco-animate"><a href="https://www.facebook.com/internationalhotel.tashkent"><span class="icon-facebook"></span></a></li>
              <li class="ftco-animate"><a href="https://www.instagram.com/hiltontashkentcityhotel/"><span class="icon-instagram"></span></a></li>
            </ul>
          </div>
        </div>
        <div class="col-md">
          <div class="ftco-footer-widget mb-4 ml-md-5">
            <h2 class="ftco-heading-2">{% trans 'Useful Links' %}</h2>
            <ul class="list-unstyled">
              <li><a href="{% url 'rooms' %}" class="py-2 d-block">{% trans 'Rooms' %}</a></li>
              <li><a href="{% url 'blog-list' %}" class="py-2 d-block">{% trans 'Blog' %}</a></li>
              <li><a href="{% url 'restaurant' %}">{% trans 'Restaurant' %}</a></li>
            </ul>
          </div>
        </div>
        <div class="col-md">
           <div class="ftco-footer-widget mb-4">
            <h2 class="ftco-heading-2">{% trans 'Privacy' %}</h2>
            <ul class="list-unstyled">
              <li><a href="{% url 'about' %}" class="py-2 d-block">{% trans 'About Us' %}</a></li>
              <li><a href="{% url 'contact' %}" class="py-2 d-block">{% trans 'Contact Us' %}</a></li>
              <li><a href="#services" class="py-2 d-block">{% trans 'Services' %}</a></li>
            </ul>
          </div>
        </div>
        <div class="col-md">
          <div class="ftco-footer-widget mb-4">
              <h2 class="ftco-heading-2">{% trans 'Have a Questions?' %}</h2>
              <div class="block-23 mb-3">
                <ul>
                  <li><span class="icon icon-map-marker"></span><span class="text">2 Islam Karimov Street, block 5
                    Tashkent, 100027, Uzbekistan</span></li>
                  <li><a href="#"><span class="icon icon-phone"></span><span class="text">+998997742878</span></a></li>
                  <li><a href="#"><span class="icon icon-envelope"></span><span class="text">hiltonuzb@gmail.com</span></a></li>
                </ul>
              </div>
          </div>
        </div>
      </div>
      <div class="row">
        <div class="col-md-12 text-center">
  
          <p>
  Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved | Hilton</p>
        </div>
      </div>
    </div>
  </footer>

templates/main2.html
{% load static %}
{% load i18n %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock %}</title>
    <!-- Font awesome link -->
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css" integrity="sha512-iBBXm8fW90+nuLcSKlbmrPcLa0OT92xO1BIsZ+ywDWZCvqsWgccV3gFoRBv0z+8dLJgyAHIhR35VZc2oM/gI1w==" crossorigin="anonymous" referrerpolicy="no-referrer" />

        <!--	Bootstrap link-->
	<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">

	 <link href="https://fonts.googleapis.com/css?family=Poppins:200,300,400,500,600,700" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Playfair+Display:400,400i,700,700i" rel="stylesheet">

   <link rel="stylesheet" href="{% static 'css/open-iconic-bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/animate.css' %}">

    <link rel="stylesheet" href="{% static 'css/owl.carousel.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/owl.theme.default.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/magnific-popup.css' %}">

    <link rel="stylesheet" href="{% static 'css/aos.css' %}">

   <link rel="stylesheet" href="{% static 'css/ionicons.min.css' %}">

    <link rel="stylesheet" href="{% static 'css/bootstrap-datepicker.css' %}">
    <link rel="stylesheet" href="{% static 'css/jquery.timepicker.css' %}">


    <link rel="stylesheet" href="{% static 'css/flaticon.css' %}">
   <link rel="stylesheet" href="{% static 'css/icomoon.css' %}">
    <link rel="stylesheet" href="{% static 'style.css' %}">

   
    
</head>
<body>
   <nav class="navbar navbar-expand-lg navbar-dark ftco_navbar bg-dark ftco-navbar-light" id="ftco-navbar">
	    <div class="container">
	      <a class="navbar-brand" href="{% url 'home' %}">Hilton</a>
	      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#ftco-nav" aria-controls="ftco-nav" aria-expanded="false" aria-label="Toggle navigation">
	        <span class="oi oi-menu"></span> Menu
	      </button>

	      <div class="collapse navbar-collapse" id="ftco-nav">
	        <ul class="navbar-nav ml-auto">
	          <li class="nav-item"><a href="{% url 'home' %}" class="nav-link">{% trans 'Home' %}</a></li>
	          <li class="nav-item"><a href="{% url 'rooms' %}" class="nav-link">{% trans 'Rooms' %}</a></li>
	          <li class="nav-item"><a href="{% url 'restaurant' %}" class="nav-link">{% trans 'Restaurant' %}</a></li>
	          <li class="nav-item"><a href="{% url 'about' %}" class="nav-link">{% trans 'About' %}</a></li>
	          <li class="nav-item"><a href="{% url 'blog-list' %}" class="nav-link">{% trans 'Blog' %}</a></li>




	          <li class="nav-item"><a href="{% url 'contact' %}" class="nav-link">{% trans 'Contact' %}</a></li>

            {% if request.user.is_authenticated %}
					{% if request.user.is_superuser %}
						<div class="nav-item dropdown">
							<a class="dropdown-toggle text-light nav-link" type="button" id="dropdownMenuButton1" data-bs-toggle="dropdown" aria-expanded="false">
							  <img src="{% static 'images/user.png' %}" alt="profile" width="25px" >
							</a>
							<ul class="dropdown-menu " aria-labelledby="dropdownMenuButton1" >
							  <li><a href="{% url 'hotel_manager:dashboard' %}" class="text-dark"><i class="fas fa-user"></i>{% trans 'Profile' %} </a></li>
								<li><a href="{% url 'logout' %}" class="text-dark"><i class="fas fa-sign-out-alt"></i>{% trans 'Log out' %}</a></li>
							  </ul>
						  </div>


						{% else %}
						<div class="nav-item dropdown">
							<a class="dropdown-toggle text-light nav-link" type="button" id="dropdownMenuButton1" data-bs-toggle="dropdown" aria-expanded="false">
							  <img src="{{request.user.guest.profile_pic.url}}" alt="profile" width="30px" height="30px" style="border-radius: 50%;">
							</a>
							<ul class="dropdown-menu " aria-labelledby="dropdownMenuButton1" >
							  <li><a href="{% url 'user_profile' %}" class="text-dark"><i class="fas fa-user"></i>{% trans 'My Bookings' %}</a></li>
							  <li><a href="{% url 'profile_settings' %}" class="text-dark"><i class="fas fa-cog"></i>{% trans 'Profile Settings' %}</a></li>
							  <li><a href="{% url 'logout' %}" class="text-dark"><i class="fas fa-sign-out-alt"></i> {% trans 'Log out' %}</a></li>
							  </ul>
						  </div>

						{% endif %}
				{% else %}
					<li class="nav-item"><a class="nav-link" href="{% url 'user_login' %}" >{% trans 'Log in' %}</a></li>
				{% endif %}
                    <li class="nav-item my-auto nav-li">


                    <form action="{% url 'set_language' %}" method="post">
                        {% csrf_token %}
                        <input name="next" type="hidden" value="{{ redirect_to }}"/>
                        {% get_current_language as LANGUAGE_CODE %}
                        {% get_available_languages as LANGUAGES %}
                        {% get_language_info_list for LANGUAGES as languages %}
                        {% for language in languages %}
                        <button type="submit" id="btn-lang" name="language" value="{{ language.code }}"
                                class="nav-lang fa-lg nav-item"
                                style="border: none;outline: none;background-color: rgba(250, 235, 215, 0);">
                            {% if language.code == 'en' %}
                            <a href="{{ language.code }}"><img src="{% static 'images/usa.png' %}" alt="" width="30"></a>
                            {% else %}
                            <a href="{{ language.code }}"><img src="{% static 'images/uzb.png' %}" alt="" width="30"></a>
                            {% endif %}
                        </button>
                        {% if language.code == 'en' %} | {% endif %}
                        {% endfor %}
                    </form>

                </li>

	        </ul>
	      </div>
	    </div>
	  </nav>
    <!-- END nav -->
    {% block content %}

    {% endblock %}

    {% include 'footer.html' %}

</body>

<script src="{% static 'js/jquery.min.js' %}"></script>
<script src="{% static 'js/jquery-migrate-3.0.1.min.js' %}"></script>
<script src="{% static 'js/popper.min.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>
<script src="{% static 'js/jquery.easing.1.3.js' %}"></script>
<script src="{% static 'js/jquery.waypoints.min.js' %}"></script>
<script src="{% static 'js/jquery.stellar.min.js' %}"></script>
<script src="{% static 'js/owl.carousel.min.js' %}"></script>
<script src="{% static 'js/jquery.magnific-popup.min.js' %}"></script>
<script src="{% static 'js/aos.js' %}"></script>
<script src="{% static 'js/jquery.animateNumber.min.js' %}"></script>
<script src="{% static 'js/bootstrap-datepicker.js' %}"></script>
<script src="{% static 'js/jquery.timepicker.min.js' %}"></script>
<script src="{% static 'js/scrollax.min.js' %}"></script>
<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBVWaKrjvy3MaE7SQ74_uJiULgl1JY0H2s&sensor=false"></script>
<script src="{% static 'js/google-map.js' %}"></script>
<script src="{% static 'js/main.js' %}"></script>
<script>
  jQuery(window).load(function() {
      $('#language').change(function() {
          window.location.replace("/" + $('#language').val() + "/");
      });
  });
  </script>
</html>

templates/navbar.html
{% load static %}
{% load i18n %}
{% load socialaccount %}

<nav class="navbar navbar-expand-lg navbar-dark ftco_navbar bg-dark ftco-navbar-light" id="ftco-navbar">
    <div class="container">
        <a class="navbar-brand" href="{% url 'home' %}">Hilton</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#ftco-nav"
                aria-controls="ftco-nav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="oi oi-menu"></span> Menu
        </button>

        <div class="collapse navbar-collapse" id="ftco-nav">
            <ul class="navbar-nav ml-auto">
                <li class="nav-item active"><a href="{% url 'home' %}" class="nav-link">{% trans 'Home' %}</a></li>
                <li class="nav-item"><a href="{% url 'rooms' %}" class="nav-link">{% trans 'Rooms' %}</a></li>
                <li class="nav-item"><a href="{% url 'restaurant' %}" class="nav-link">{% trans 'Restaurant' %}</a></li>
                <li class="nav-item"><a href="{% url 'about' %}" class="nav-link">{% trans 'About' %}</a></li>
                <li class="nav-item"><a href="{% url 'blog-list' %}" class="nav-link">{% trans 'Blog' %}</a></li>
                <li class="nav-item"><a href="{% url 'contact' %}" class="nav-link">{% trans 'Contact' %}</a></li>


                {% if request.user.is_authenticated %}
                {% if request.user.is_superuser %}
                <div class="nav-item dropdown">
                    <a class="dropdown-toggle text-light nav-link" type="button" id="dropdownMenuButton1"
                       data-bs-toggle="dropdown" aria-expanded="false">
                        <img src="{% static 'images/user.png' %}" alt="profile" width="25px">
                    </a>
                    <ul class="dropdown-menu " aria-labelledby="dropdownMenuButton1">
                        <li><a href="{% url 'hotel_manager:dashboard' %}" class="text-dark"><i class="fas fa-user"></i>
                            {% trans 'Profile' %} </a></li>
                        <li><a href="{% url 'logout' %}" class="text-dark"><i class="fas fa-sign-out-alt"></i>
                            {% trans 'Log out' %}</a></li>
                    </ul>
                </div>


                {% else %}
                <div class="nav-item dropdown">
                    <a class="dropdown-toggle text-light nav-link" type="button" id="dropdownMenuButton1"
                       data-bs-toggle="dropdown" aria-expanded="false">
                        <img src="{{request.user.guest.profile_pic.url}}" alt="profile" width="30px" height="30px"
                             style="border-radius: 50%;">
                    </a>
                    <ul class="dropdown-menu " aria-labelledby="dropdownMenuButton1">
                        <li><a href="{% url 'user_profile' %}" class="text-dark"><i class="fas fa-user"></i>
                            {% trans 'My Bookings' %}</a></li>
                        <li><a href="{% url 'profile_settings' %}" class="text-dark"><i class="fas fa-cog"></i>
                            {% trans 'Profile Settings' %}</a></li>
                        <li><a href="{% url 'logout' %}" class="text-dark"><i class="fas fa-sign-out-alt"></i>
                            {% trans 'Log out' %}</a></li>
                    </ul>
                </div>

                {% endif %}
                {% else %}
                <li class="nav-item"><a href="#login" class="trigger-btn nav-link" data-toggle="modal">
                    {% trans 'Log in' %}</a></li>
                {% endif %}
                <li class="nav-item my-auto nav-li">


                    <form action="{% url 'set_language' %}" method="post">
                        {% csrf_token %}
                        <input name="next" type="hidden" value="{{ redirect_to }}"/>
                        {% get_current_language as LANGUAGE_CODE %}
                        {% get_available_languages as LANGUAGES %}
                        {% get_language_info_list for LANGUAGES as languages %}
                        {% for language in languages %}
                        <button type="submit" id="btn-lang" name="language" value="{{ language.code }}"
                                class="nav-lang fa-lg"
                                style="border: none;outline: none;background-color: rgba(250, 235, 215, 0); display:inline;">
                            {% if language.code == 'en' %}
                            <a href="{{ language.code }}"><img src="{% static 'images/usa.png' %}" alt="" width="30"></a>
                            {% else %}
                            <a href="{{ language.code }}"><img src="{% static 'images/uzb.png' %}" alt="" width="30"></a>
                            {% endif %}
                        </button>
                        {% if language.code == 'en' %} | {% endif %}
                        {% endfor %}
                    </form>

                </li>
            </ul>
        </div>
    </div>

</nav>
<!-- END nav -->


<!-- LOGIN MODAL  -->
<form action="" method="post">
    {% csrf_token %}
    <div id="login" class="modal fade">
        <div class="modal-dialog modal-login">
            <div class="modal-content ">
                <div class="modal-header text-center">
                    <h4 class="modal-title w-100">Login In</h4>
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                </div>
                <div class="modal-body">
                    <form action="/examples/actions/confirmation.php" method="post">
                        <div class="form-group">
                            <input type="text" class="form-control" name="username" placeholder="Username"
                                   required="required">
                        </div>
                        <div class="form-group">
                            <input type="password" class="form-control" name="password" placeholder="Password"
                                   required="required">
                        </div>
                        <div class="form-group">
                            <button type="submit" class="btn btn-primary btn-lg btn-block login-btn">{% trans 'Login' %}</button>
                        </div>
                        <div class="or-seperator"><i>{% trans 'or' %}</i></div>
                        <p class="text-center">{% trans 'Login with your google account' %}</p>
                        <div class="text-center social-btn">
                            <a href="{% provider_login_url 'google' %}" class="btn btn-primary"><i
                                    class="fa fa-google"></i>Google</a>
                        </div>
                    </form>
                </div>
                <p class="text-center text-muted small">{% trans "Don't have an account?" %} <a
                        href="{% url 'user_signup' %}">{% trans 'Sign up here!' %}</a></p>

            </div>
        </div>
    </div>
</form>
<!-- end Login Modal  -->

templates/pagination.html
{% load i18n %}
<div class="pagination text-center row mt-5">
    <span class="step-links">{% if page.has_previous %}<a class="btn btn-outline-info" href="?page={{ page.previous_page_number }}">{% trans 'Previous' %}</a>
    {% endif %}
    <span class="current">Page {{ page.number }} of {{ page.paginator.num_pages }}.</span>{% if page.has_next %}
    <a class="btn btn-outline-info" href="?page={{ page.next_page_number }}">{% trans 'Next' %}</a>{% endif %}</span>
</div>
